// 받을각 - 지원제도 데이터셋
// 모든 항목은 실존하는 대한민국 정부/지자체 공공 지원제도를 기반으로 합니다.
// 정확한 최신 자격요건·지원금액·예산 소진 여부는 반드시 공식 출처에서 재확인하세요.
// (본 프로젝트는 K-AI 콘텐츠 공모전 데모용으로, 수치는 일반적인 기준을 요약한 것입니다.)

const PROGRAMS = [
  {
    id: "youth-rent",
    name: "청년월세 특별지원",
    agency: "국토교통부",
    tagline: "무주택 청년 자취생에게 월세 일부를 최대 1년간 지원",
    summary: "부모와 따로 거주하며 월세를 내는 만 19~34세 무주택 청년에게 매달 일정 금액의 월세를 지원합니다. 청년 본인 소득과 부모(원가구) 소득 기준을 함께 봅니다.",
    howTo: "복지로 또는 거주지 시·군·구청 홈페이지에서 온라인 신청",
    sourceName: "복지로",
    sourceUrl: "https://www.bokjiro.go.kr",
    ages: ["20s", "30s"],
    statuses: ["student", "jobseeker", "worker", "freelancer", "unemployed"],
    housing: ["alone_rent"],
    incomes: ["low", "mid_low", "unknown"],
    keywords: ["월세", "자취", "전세", "보증금", "주거비", "독립", "원룸", "방세", "집세", "집값"]
  },
  {
    id: "national-scholarship",
    name: "국가장학금",
    agency: "한국장학재단",
    tagline: "소득구간(분위)에 따라 등록금을 지원하는 대학생 장학금",
    summary: "대학(원)생을 대상으로 가구 소득·재산을 8구간으로 나누어 구간별로 등록금 일부 또는 전액을 지원합니다. 매 학기 신청해야 합니다.",
    howTo: "한국장학재단 홈페이지에서 학기별 신청기간에 온라인 신청",
    sourceName: "한국장학재단",
    sourceUrl: "https://www.kosaf.go.kr",
    ages: ["10s", "20s", "30s"],
    statuses: ["student"],
    housing: [],
    incomes: ["low", "mid_low", "mid", "unknown"],
    keywords: ["등록금", "학자금", "대학", "장학금", "학비"]
  },
  {
    id: "youth-hope-account",
    name: "청년도약계좌",
    agency: "금융위원회",
    tagline: "5년 부으면 정부가 얹어주는 청년 목돈마련 적금",
    summary: "만 19~34세 청년이 매달 일정 금액을 납입하면 소득 수준에 따라 정부기여금을 더해주고, 이자소득에 비과세 혜택을 주는 자산형성 상품입니다.",
    howTo: "은행 앱(농협·신한·국민 등) 또는 서민금융진흥원에서 가입 신청",
    sourceName: "서민금융진흥원",
    sourceUrl: "https://www.kinfa.or.kr",
    ages: ["20s", "30s"],
    statuses: ["student", "jobseeker", "worker", "freelancer"],
    housing: [],
    incomes: ["mid_low", "mid", "unknown"],
    keywords: ["적금", "목돈", "자산", "저축", "재테크", "저금", "돈이 안 모", "모으"]
  },
  {
    id: "exam-fee-support",
    name: "청년 국가기술자격시험 응시료 지원",
    agency: "고용노동부",
    tagline: "만 34세 이하 청년의 자격증 응시료를 절반으로",
    summary: "한국산업인력공단이 시행하는 국가기술자격 시험에 응시하는 만 19~34세 청년에게 응시료의 50%를 지원합니다(연 3회 한도). 기사·산업기사·기능사 등 대부분의 종목에 적용됩니다.",
    howTo: "큐넷(Q-Net)에서 원서 접수 시 감면 대상 선택",
    sourceName: "큐넷",
    sourceUrl: "https://www.q-net.or.kr",
    ages: ["20s", "30s"],
    statuses: ["student", "jobseeker", "worker", "freelancer", "unemployed"],
    housing: [],
    incomes: ["low", "mid_low", "mid", "unknown"],
    keywords: ["자격증", "시험", "응시료", "기사", "산업기사", "기능사", "스펙"]
  },
  {
    id: "job-seeker-support",
    name: "국민취업지원제도",
    agency: "고용노동부",
    tagline: "구직활동을 하면 최대 6개월간 매달 현금을 지원",
    summary: "저소득 구직자·청년 미취업자 등을 대상으로 취업 상담·훈련을 연계하고, 요건 충족 시 매달 구직촉진수당을 지급합니다.",
    howTo: "고용24 또는 가까운 고용센터에서 신청",
    sourceName: "고용24",
    sourceUrl: "https://www.work24.go.kr",
    ages: ["20s", "30s", "40s"],
    statuses: ["jobseeker", "unemployed", "freelancer"],
    housing: [],
    incomes: ["low", "mid_low", "unknown"],
    keywords: ["취업", "구직", "실업", "이력서", "면접", "구직활동", "취준", "백수", "일자리"]
  },
  {
    id: "youth-challenge",
    name: "청년도전지원사업",
    agency: "고용노동부",
    tagline: "구직을 오래 쉰 청년의 첫걸음을 돕는 프로그램",
    summary: "장기간 구직활동을 하지 않은 만 18~34세 청년에게 자신감 회복 프로그램과 참여수당을 지원해 다시 구직시장에 나설 수 있도록 돕습니다.",
    howTo: "고용24 또는 지역 청년센터에서 신청",
    sourceName: "고용24",
    sourceUrl: "https://www.work24.go.kr",
    ages: ["20s", "30s"],
    statuses: ["jobseeker", "unemployed"],
    housing: [],
    incomes: ["low", "mid_low", "unknown"],
    keywords: ["구직", "취업준비", "자신감", "고립", "니트"]
  },
  {
    id: "eitc",
    name: "근로장려금",
    agency: "국세청",
    tagline: "저소득 근로자·사업자 가구에 매년 현금으로 환급",
    summary: "일은 하지만 소득이 낮은 가구에 가구 유형별 소득·재산 기준을 충족하면 연 1회 현금성 장려금을 지급합니다.",
    howTo: "홈택스 또는 손택스 앱에서 매년 5월(정기) 신청",
    sourceName: "국세청 홈택스",
    sourceUrl: "https://www.hometax.go.kr",
    ages: ["20s", "30s", "40s"],
    statuses: ["worker", "freelancer"],
    housing: [],
    incomes: ["low", "mid_low"],
    keywords: ["소득", "세금", "환급", "장려금", "근로"]
  },
  {
    id: "child-eitc",
    name: "자녀장려금",
    agency: "국세청",
    tagline: "자녀를 키우는 저소득 가구에 자녀 수만큼 지원",
    summary: "18세 미만 부양자녀가 있는 저소득 가구를 대상으로 자녀 1인당 일정 금액을 현금으로 지급합니다.",
    howTo: "홈택스 또는 손택스 앱에서 매년 5월(정기) 신청",
    sourceName: "국세청 홈택스",
    sourceUrl: "https://www.hometax.go.kr",
    ages: ["20s", "30s", "40s"],
    statuses: ["worker", "freelancer", "unemployed"],
    housing: [],
    incomes: ["low", "mid_low"],
    keywords: ["자녀", "양육", "육아", "아이"]
  },
  {
    id: "culture-card",
    name: "문화누리카드",
    agency: "문화체육관광부",
    tagline: "기초수급·차상위 대상 연간 문화생활비 지원카드",
    summary: "기초생활수급자·차상위계층에게 매년 일정 금액을 충전해주어 영화, 공연, 도서, 여행, 체육활동 등에 자유롭게 사용할 수 있습니다.",
    howTo: "문화누리카드 홈페이지 또는 주민센터에서 신청",
    sourceName: "문화누리카드",
    sourceUrl: "https://www.mnuri.kr",
    ages: ["10s", "20s", "30s", "40s", "senior"],
    statuses: ["student", "jobseeker", "worker", "freelancer", "unemployed", "senior_life"],
    housing: [],
    incomes: ["low"],
    keywords: ["문화", "여행", "영화", "공연", "책", "여가"]
  },
  {
    id: "energy-voucher",
    name: "에너지바우처",
    agency: "한국에너지공단",
    tagline: "저소득 가구의 냉난방비를 계절별로 지원",
    summary: "기초생활수급자 중 노인·영유아·장애인·임산부·중증질환자 등이 포함된 가구에 여름철 냉방비, 겨울철 난방비를 바우처로 지원합니다.",
    howTo: "복지로 또는 읍면동 주민센터에서 신청",
    sourceName: "에너지바우처",
    sourceUrl: "https://www.energyvoucher.go.kr",
    ages: ["10s", "20s", "30s", "40s", "senior"],
    statuses: ["senior_life", "unemployed", "worker", "freelancer"],
    housing: [],
    incomes: ["low"],
    keywords: ["전기세", "난방비", "냉방비", "에너지", "가스비"]
  },
  {
    id: "k-pass",
    name: "K-패스",
    agency: "국토교통부",
    tagline: "대중교통 자주 타면 다음 달 요금 일부를 환급",
    summary: "월 15회 이상 대중교통을 이용하면 지출액의 일정 비율(청년·저소득은 더 높은 비율)을 다음 달에 환급해주는 교통비 절감 카드입니다.",
    howTo: "K-패스 홈페이지 또는 카드사 앱에서 카드 발급 후 회원가입",
    sourceName: "K-패스",
    sourceUrl: "https://korea-pass.kr",
    ages: ["10s", "20s", "30s", "40s", "senior"],
    statuses: ["student", "jobseeker", "worker", "freelancer", "unemployed", "senior_life"],
    housing: [],
    incomes: ["low", "mid_low", "mid", "unknown"],
    keywords: ["대중교통", "버스", "지하철", "교통비", "출퇴근", "버스비"]
  },
  {
    id: "jeonse-loan",
    name: "청년전용 버팀목전세자금대출",
    agency: "주택도시기금",
    tagline: "무주택 청년을 위한 저금리 전세자금 대출",
    summary: "만 19~34세 무주택 세대주(예정자) 청년에게 시중은행보다 낮은 금리로 전세보증금 대출을 지원합니다.",
    howTo: "주택도시기금 홈페이지 또는 우리·국민·신한·농협은행 방문 신청",
    sourceName: "주택도시기금",
    sourceUrl: "https://nhuf.molit.go.kr",
    ages: ["20s", "30s"],
    statuses: ["student", "jobseeker", "worker", "freelancer"],
    housing: ["alone_rent"],
    incomes: ["mid_low", "mid", "unknown"],
    keywords: ["전세", "전세자금", "대출", "보증금", "이사"]
  },
  {
    id: "mind-health",
    name: "청년 마음건강 지원사업",
    agency: "한국건강가정진흥원",
    tagline: "만 19~34세 청년 심리상담을 최대 10회 지원",
    summary: "우울, 불안, 번아웃 등을 겪는 청년에게 전문 심리상담 비용의 상당 부분을 바우처로 지원합니다.",
    howTo: "청년센터 또는 정신건강복지센터에서 신청",
    sourceName: "복지로",
    sourceUrl: "https://www.bokjiro.go.kr",
    ages: ["20s", "30s"],
    statuses: ["student", "jobseeker", "worker", "freelancer", "unemployed"],
    housing: [],
    incomes: ["low", "mid_low", "mid", "unknown"],
    keywords: ["우울", "불안", "스트레스", "상담", "마음건강", "번아웃", "심리", "힘들", "외로", "지쳤", "멘탈", "무기력"]
  },
  {
    id: "unemployment-benefit",
    name: "실업급여(구직급여)",
    agency: "고용노동부",
    tagline: "비자발적으로 퇴사했다면 구직활동 중 지급되는 급여",
    summary: "고용보험에 가입되어 있다가 비자발적 사유로 퇴사한 경우, 적극적으로 구직활동을 하는 조건으로 일정 기간 급여를 지급합니다.",
    howTo: "고용24에서 수급자격 신청 후 거주지 고용센터 방문",
    sourceName: "고용24",
    sourceUrl: "https://www.work24.go.kr",
    ages: ["20s", "30s", "40s"],
    statuses: ["unemployed", "jobseeker"],
    housing: [],
    incomes: [],
    keywords: ["퇴사", "실업", "구직급여", "해고", "권고사직", "잘렸", "퇴직", "그만뒀"]
  },
  {
    id: "basic-pension",
    name: "기초연금",
    agency: "보건복지부",
    tagline: "만 65세 이상 소득 하위 70% 어르신께 매달 지급",
    summary: "만 65세 이상이면서 소득인정액이 선정기준액 이하인 어르신에게 매달 일정 금액의 연금을 지급합니다.",
    howTo: "복지로 또는 국민연금공단·읍면동 주민센터에서 신청",
    sourceName: "복지로",
    sourceUrl: "https://www.bokjiro.go.kr",
    ages: ["senior"],
    statuses: ["senior_life"],
    housing: [],
    incomes: ["low", "mid_low", "unknown"],
    keywords: ["어르신", "노후", "연금", "노인"]
  },
  {
    id: "senior-job",
    name: "노인일자리 및 사회활동지원사업",
    agency: "한국노인인력개발원",
    tagline: "만 65세 이상 어르신을 위한 일자리·활동 지원",
    summary: "공익활동형, 사회서비스형, 시장형 등 다양한 형태로 어르신께 일자리와 활동비를 지원해 사회참여를 돕습니다.",
    howTo: "가까운 노인일자리 수행기관(시니어클럽 등) 또는 복지로에서 신청",
    sourceName: "한국노인인력개발원",
    sourceUrl: "https://www.kordi.or.kr",
    ages: ["senior"],
    statuses: ["senior_life"],
    housing: [],
    incomes: ["low", "mid_low", "unknown"],
    keywords: ["일자리", "활동", "소일거리", "노인", "사회참여"]
  },
  {
    id: "jeonse-guarantee-fee",
    name: "청년 전세보증금 반환보증 보증료 지원",
    agency: "지자체(시·도)",
    tagline: "전세사기 걱정 청년의 보증료를 지자체가 대신 지원",
    summary: "무주택 청년이 전세보증금반환보증 상품에 가입할 때 드는 보증료 일부를 지자체가 환급 지원해 전세사기 피해를 예방합니다.",
    howTo: "거주지 시·군·구청 홈페이지 또는 정부24에서 신청",
    sourceName: "정부24",
    sourceUrl: "https://www.gov.kr",
    ages: ["20s", "30s"],
    statuses: ["student", "jobseeker", "worker", "freelancer"],
    housing: ["alone_rent"],
    incomes: ["low", "mid_low", "mid", "unknown"],
    keywords: ["전세사기", "보증금", "반환보증", "전세"]
  },
  {
    id: "seoul-learn",
    name: "온라인 교육격차 해소 플랫폼 (예: 서울런)",
    agency: "지자체 교육청",
    tagline: "저소득 가구 초중고생에게 인터넷 강의를 무료로",
    summary: "기초수급·차상위·한부모가정 등 저소득 가구의 초·중·고 학생에게 유명 인터넷 강의를 무료로 이용할 수 있게 지원하는 지자체 플랫폼입니다.",
    howTo: "거주 지자체의 교육 플랫폼 홈페이지에서 회원가입 후 대상 확인",
    sourceName: "정부24",
    sourceUrl: "https://www.gov.kr",
    ages: ["10s"],
    statuses: ["student"],
    housing: [],
    incomes: ["low", "mid_low"],
    keywords: ["인강", "학원비", "교육격차", "사교육", "공부"]
  },
  {
    id: "learning-card",
    name: "국민내일배움카드",
    agency: "고용노동부",
    tagline: "이직·재취업 준비생을 위한 직업훈련비 지원카드",
    summary: "재직자, 자영업자, 구직자 등 대부분의 국민에게 직업훈련 비용을 카드 형태로 지원해 새로운 기술과 자격증 취득을 돕습니다.",
    howTo: "고용24에서 카드 발급 신청 후 훈련과정 선택",
    sourceName: "고용24",
    sourceUrl: "https://www.work24.go.kr",
    ages: ["20s", "30s", "40s"],
    statuses: ["jobseeker", "worker", "freelancer", "unemployed"],
    housing: [],
    incomes: ["low", "mid_low", "mid", "unknown"],
    keywords: ["직업훈련", "자격증", "이직", "새로운기술", "배움", "학원", "국비", "코딩", "부트캠프", "인강"]
  }
];
